### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by kiwifb** [JobinJohan/jupyterhub-utility-scripts#1]
Hi found your scripts from another github issue and I think they will be a useful base for my own work.
1) the script `delete-user-from-system.sh` goes
```
for dir in ./jupyter-*$PATTERN*
```
which implies it is run from a particular folder. But this is mentioned nowhere in the readme file.

2) because of my usage to reset the hub for course the next semester, I don't want to delete users matching a pattern, I want to wipe out all user expect those from a list of teacher and assistant. Because I get username from AD, I cannot just rely on patterns to distinguish them. So, my own version will have a different way to gather users (from the sqlite3) and I will check them against an exclusion list.

3) in that spirit, how would I change https://github.com/JobinJohan/jupyterhub-utility-scripts/blob/main/delete-user-from-system.sh#L50 to add users instead? My current process is to add them on the front end and run a script afterwards to create home dirs and add them to the allowed users in AD. Fortunately, unlike for deletion you can add a bunch at once but scripting the process entirely would be nice.

**Comment by JobinJohan** [comment]
Hi,

You're right, I forgot to mention that the script is run from the `/home` folder, in which the directories of all users are created.

Regarding your question, the easiest way to add multiple users at the same time is to make a POST request (usernames in the request body) to the JupyterHub API (https://jupyterhub.readthedocs.io/en/stable/reference/rest-api.html#/default/post_users) using the `/users` route.

Have a nice day 😀

**Comment by kiwifb** [comment]
Which made me think afterwards, why do you ask to give the machine IP address since it has to run locally? On the other hand I got caught out because I am running on port 8000 and a base url (`c.JupyterHub.base_url`) all of which had to be added giving `127.0.0.1:8000/base_url`.

**Comment by kiwifb** [comment]
For the record this is what I am going with for the user selection part. I wipe all non jupyterhub admins. Pattern could be re-added if wanted
```
#! /bin/bash
# Author: Johan Jobin, 2022 [https://github.com/JobinJohan/jupyterhub-utility-scripts/blob/main/delete-user-from-system.sh]
# Author: François Bissey 2022
# Description: script that completely deletes users from JupyterHub
# Notes:
#	1. the script deletes the jupyterhub all users from the .sqlite database, and their associated Linux account and removes their /home directory.
#	2. to run the script first do "chmod +x delete-user-from-system.sh" and then "./delete-user-from-system.sh TOKEN CONFIG" where:
#          - TOKEN is a token generated on JupyterHub to interact with the API.
#          - CONFIG is optionally the path to jupyterhub_conf.py, if not provided, it is assumed.

read_jhub_config() {
	# Finding jupyterhub configuration's info
	# First extraction with awk. This started as
	# SQLITEDB=$(awk '{ if ($1 == "c.JupyterHub.db_url" ) print $3}' "${CONFIG}")
	# But had to be generalised for other jupyterhub settings.
	# Just using a shell variable in awk leads to issues, so use awk variables instead as per manual
	# https://www.gnu.org/software/gawk/manual/html_node/Using-Shell-Variables.html
	local read_config=$(awk -v pattern=$1 '{ if ($1 ~ pattern ) print $3}' "${CONFIG}")
	# Configs are usually given in the form "u'some_string'" so we have to clean the potential leading "u"
	# and the single quotes. "tr -d" remove all instances of a character. Hopefully no configuration strings
	# have a single quote in them. Use shell substitution for the leading "u", using "tr" to eliminate it would lead
	# to stuff like jupyter -> jpyter.
	read_config=$(echo "${read_config#u}" | tr -d "'")
	echo "${read_config}"
}

if [ $# -ne 1 ]; then
	echo "Please at least a JupyterHub token, then optionnally the path of the jupyterhub configuration file"
	exit 1
fi

TOKEN=$1
CONFIG=$2

# default jupyterhub configuration
if [ -z ${CONFIG} ]; then
	CONFIG="/etc/jupyterhub/jupyterhub_config.py"
fi

SQLITEDB=$(read_jhub_config c.JupyterHub.db_url)
HOST=$(read_jhub_config c.JupyterHub.ip)
PORT=$(read_jhub_config c.JupyterHub.port)
BASEURL=$(read_jhub_config c.JupyterHub.base_url)

# Assemble the full url of the jupyterhub
HOST="${HOST}:${PORT}${BASEURL}"

echo "full jupyterhub url ${HOST}"

# General use case
#SQLITE3CMD=`which sqlite3`
# jupyterhub installed from conda
SQLITE3CMD="/opt/miniconda/bin/sqlite3"

# List non-admins users
list=`${SQLITE3CMD} "${SQLITEDB}" 'SELECT name FROM users WHERE admin=FALSE'`
counter=`${SQLITE3CMD} "${SQLITEDB}" 'SELECT COUNT(name) FROM users WHERE admin=FALSE'`
# List the admin users
staff_list=`${SQLITE3CMD} "${SQLITEDB}" 'SELECT name FROM users WHERE admin'`

echo "Here is the list of users that will be deleted:"

for user in ${list}; do
	echo "${user}"
done

if [ "$counter" -eq 0 ]; then
	echo $counter
	echo ">>> No user to delete"
	exit 1
fi

echo "-------------------------------------------------"
echo ">>> Total of users who will be deleted:" $counter
echo -e "\n"

echo "-------------------------------------------------"
echo ">>> The following users are marked as administrator and will be kept:"
for user in ${staff_list}; do
	echo "- ${user}"
done
echo ">>> To remove them with this script, remove their admin privileges."
```

**Comment by JobinJohan** [comment]
You are right, there is no need to ask the user for the IP address of the machine since the code is running locally 👍 

Thank you for sharing your code for user selection. It is a good idea to make queries directly on the SQLite database rather than going through the API as I did!

Have a good day.
